export const GAME_CONTENT = {
  dry: [
    "Do your best impression of a chicken laying an egg",
    "Speak in a British accent for the next 3 rounds",
    "Let someone tickle you for 30 seconds without laughing",
    "Recreate your most embarrassing moment",
    "Do 20 jumping jacks while singing the alphabet",
    "Pretend you're a news anchor reporting on this game",
    "Dance like nobody's watching for 60 seconds",
    "Talk like a robot until your next turn",
    "Do your best celebrity impression",
    "Wear socks on your hands for the next round",
    "Bark like a dog every time someone says your name",
    "Tell everyone your most embarrassing childhood nickname",
    "Do your best drunk walk across the room",
    "Speak only in questions for the next 2 rounds",
    "Let the group style your hair however they want",
    "Act out your morning routine in fast forward",
    "Talk in third person for the next 3 rounds",
    "Do an interpretive dance of your day today",
    "Moonwalk everywhere for the next round",
    "Pretend you're a telemarketer and try to sell something random",
    "Do your best impression of the person to your left",
    "Sing everything you say for the next 2 rounds",
    "Act like a mime for the next 60 seconds",
    "Do your worst pickup line on the person across from you",
    "Pretend you're underwater for 30 seconds",
    "Do 10 pushups while complimenting everyone",
    "Walk on your knees for the next round",
    "Act out a dramatic soap opera scene with yourself",
    "Beatbox for 30 seconds",
    "Do the worm or your best attempt at it",
    "Talk like a pirate until your next turn",
    "Act like you're in a musical for the next round",
    "Do your best runway model walk",
    "Pretend you're a sports commentator narrating this game",
    "Spin in circles 10 times then try to walk straight",
    "Do an air guitar solo",
    "Act like a teacher giving a lesson on something ridiculous",
    "Pretend you're in a horror movie for 30 seconds",
    "Do your best evil villain laugh",
    "Act like you're on a cooking show making a disgusting meal",
    "Do your best opera singer impression",
    "Pretend you're a fashion designer critiquing everyone's outfits",
    "Do the chicken dance",
    "Act like you're a tour guide showing off this room",
    "Do your best workout instructor impression",
    "Pretend you're an auctioneer",
    "Do a commercial for this game",
    "Act like you're giving an Oscar acceptance speech",
    "Do your best dinosaur impression",
    "Pretend you're a parent scolding their child"
  ],

  wet: [
    "Kiss the person to your right on the cheek",
    "Give someone a lap dance for 30 seconds",
    "Tell the group your wildest fantasy location",
    "Let someone draw on you with lipstick",
    "Whisper something dirty in someone's ear",
    "Show everyone your last three DMs",
    "Do a sexy dance for the group",
    "Let someone give you a hickey",
    "Tell everyone your body count",
    "Describe your ideal type in explicit detail",
    "Let the group read your last 5 texts",
    "Give your best bedroom eyes to everyone",
    "Tell the group your most recent hookup story",
    "Let someone sit on your lap for the next round",
    "Show the group your spiciest photo",
    "Tell everyone what you're wearing under your clothes",
    "Let someone feed you seductively",
    "Describe your last wet dream",
    "Give someone a sensual shoulder massage",
    "Tell the group your favorite position",
    "Let someone blindfold you for the next dare",
    "Bite your lip and make eye contact with everyone",
    "Tell everyone your dirtiest pickup line",
    "Let the group vote on who you should kiss",
    "Demonstrate your signature move",
    "Tell the group where you've hooked up in public",
    "Let someone trace their finger along your lips",
    "Describe the last time you got turned on",
    "Give someone a foot massage",
    "Tell everyone what type of content you watch",
    "Let someone whisper in your ear what they want to do to you",
    "Show the group your search history",
    "Tell everyone your biggest turn on",
    "Let the group choose someone to grind on you",
    "Describe your most adventurous experience",
    "Tell the group your safe word",
    "Let someone pour a shot in your mouth",
    "Give someone your best bedroom voice",
    "Tell everyone what you're into",
    "Let someone undo one button or zipper",
    "Describe the last time you couldn't keep your hands to yourself",
    "Tell the group your most sensitive spot",
    "Let someone lick whipped cream off your finger",
    "Give someone a hickey wherever they choose",
    "Tell everyone the last time you got caught",
    "Let the group see your dating app profile",
    "Describe your favorite foreplay activity",
    "Tell everyone your wildest hookup location",
    "Let someone take a body shot off you",
    "Give your sexiest look to the camera"
  ],

  slippery: [
    "Make out with the person of the group's choosing for 30 seconds",
    "Strip down to your underwear for the next 3 rounds",
    "Let someone leave a mark anywhere they want",
    "Take off one piece of clothing",
    "Give someone a full body massage",
    "Let the group tie you up for the next round",
    "Do a body shot off someone",
    "Let someone put ice down your shirt",
    "Kiss someone on the lips for 10 seconds",
    "Let someone spank you 5 times",
    "Take a shot off someone's body part of their choice",
    "Let two people make out in front of you while you watch",
    "Remove someone else's piece of clothing",
    "Let someone mark you with their teeth",
    "Make out with two people back to back",
    "Let the group cover you in whipped cream and lick it off",
    "Give someone a striptease",
    "Let someone pour alcohol on you and lick it off",
    "Kiss everyone in the group on the lips",
    "Let someone handcuff or tie your hands for 2 rounds",
    "Do whatever the last person who went tells you",
    "Let someone give you a cold shower dare",
    "Recreate your loudest moment",
    "Let the group choose two people to sandwich you",
    "Strip completely and stay that way for one round",
    "Let someone sit on your face for 10 seconds",
    "Give the group a show they won't forget",
    "Let someone put their hands wherever they want for 30 seconds",
    "Kiss your way up someone's arm",
    "Let the group vote on your most attractive feature and show it off",
    "Do 7 minutes in heaven with someone",
    "Let someone blindfold and feed you",
    "Give someone a hickey on their neck",
    "Let two people touch you at the same time",
    "Take a body shot and give a body shot",
    "Let someone take off your top",
    "Make the dirtiest face you can at everyone",
    "Let someone trace their tongue on your neck",
    "Kiss someone's inner thigh",
    "Let the group put you in a compromising position",
    "Give someone a lap dance while making eye contact",
    "Let someone unhook or remove your bra/shirt",
    "Demonstrate your favorite position using a person",
    "Let someone pour ice water down your pants",
    "Make out with the hottest person here",
    "Let someone bite you wherever they want",
    "Flash the group",
    "Let someone kiss you anywhere but your lips",
    "Give the group your best performance",
    "Switch underwear with someone"
  ],

  foreplay: [
    "What's the kinkiest thing you've ever done?",
    "What's your biggest turn-off?",
    "Have you ever hooked up with someone here?",
    "What's your favorite part of someone's body?",
    "What's the longest you've gone without?",
    "Have you ever been caught in the act?",
    "What's your go-to move?",
    "What's the weirdest place you've done it?",
    "Have you ever sent nudes to the wrong person?",
    "What's your body count?",
    "What's the most public place you've hooked up?",
    "Have you ever hooked up with a friend's ex?",
    "What's your wildest fantasy?",
    "What's something you've always wanted to try?",
    "Have you ever cheated?",
    "What's your favorite position?",
    "Have you ever had a threesome?",
    "What's the most people you've been with at once?",
    "What's your biggest sexual regret?",
    "Have you ever been in a friends with benefits situation?",
    "What's the quickest you've hooked up with someone?",
    "Have you ever hooked up with a stranger?",
    "What's your safe word?",
    "Have you ever been walked in on?",
    "What's the longest you've made someone wait?",
    "Have you ever recorded yourself?",
    "What's your favorite type of content to watch?",
    "Have you ever done it in a car?",
    "What's the most times in one day?",
    "Have you ever had someone use a toy on you?",
    "What's your most sensitive spot?",
    "Have you ever hooked up with a coworker?",
    "What's something that instantly turns you on?",
    "Have you ever been with someone way older or younger?",
    "What's the dirtiest text you've ever sent?",
    "Have you ever done a one night stand?",
    "What's your preferred underwear on someone?",
    "Have you ever been tied up?",
    "What's the roughest you like it?",
    "Have you ever dominated someone?",
    "What's your favorite thing someone's done to you?",
    "Have you ever been with more than one person in a week?",
    "What's something you've done that you'd never tell your parents?",
    "Have you ever hooked up at a party?",
    "What's your biggest fantasy involving someone here?",
    "Have you ever sent a risky photo?",
    "What's the most adventurous thing you've tried?",
    "Have you ever been blindfolded?",
    "What's something you'd only do drunk?",
    "Who here would you most want to hook up with?"
  ]
};
